load("//build:build_module.bzl", "build_module")
load("//build:build_binary.bzl", "build_binary")

build_module(
    name = "hello-world-lib",
    main_deps = [
    ],
)

build_binary(
    name = "hello-world",
    main_class = "helloworld.Main",
    main_deps = [
    ],
)
