java_import(
    name = "junit",
    jars = [
        "junit/junit-4.13.2.jar",
        "junit/hamcrest-2.2.jar",
    ],
    visibility = [ "//visibility:public" ],
)

java_import(
    name = "takari-cpsuite",
    jars = [
        "takari-cpsuite/takari-cpsuite-1.2.7.jar",
    ],
    visibility = [ "//visibility:public" ],
)