java_import(
    name = "slf4j",
    jars = [
        "slf4j/slf4j-api-2.0.7.jar",
        "slf4j/slf4j-simple-2.0.7.jar",
    ],
    visibility = [ "//visibility:public" ],
)

java_import(
    name = "junit",
    jars = [
        "junit/junit-4.13.2.jar",
        "junit/hamcrest-2.2.jar",
    ],
    visibility = [ "//visibility:public" ],
)